export const homeConstants = {
    HOME_REQUEST: 'USERS_HOME_REQUEST',
    HOME_SUCCESS: 'USERS_HOME_SUCCESS',
    HOME_FAILURE: 'USERS_HOME_FAILURE',

    RETAILER_REQUEST: 'USERS_RETAILER_REQUEST',
    RETAILER_SUCCESS: 'USERS_RETAILER_SUCCESS',
    RETAILER_FAILURE: 'USERS_RETAILER_FAILURE',

    FUEL_REQUEST: 'USERS_FUEL_REQUEST',
    FUEL_SUCCESS: 'USERS_FUEL_SUCCESS',
    FUEL_FAILURE: 'USERS_FUEL_FAILURE',

    FUEL_PRICE_REQUEST: 'USERS_FUEL_PRICE_REQUEST',
    FUEL_PRICE_SUCCESS: 'USERS_FUEL_PRICE_SUCCESS',
    FUEL_PRICE_FAILURE: 'USERS_FUEL_PRICE_FAILURE',

    DELIVERY_TAX_REQUEST: 'USERS_DELIVERY_TAX_REQUEST',
    DELIVERY_TAX_SUCCESS: 'USERS_DELIVERY_TAX_SUCCESS',
    DELIVERY_TAX_FAILURE: 'USERS_DELIVERY_TAX_FAILURE',

    SCHEDULE_DELIVERY_REQUEST: 'USERS_SCHEDULE_DELIVERY_REQUEST',
    SCHEDULE_DELIVERY_SUCCESS: 'USERS_SCHEDULE_DELIVERY_SUCCESS',
    SCHEDULE_DELIVERY_FAILURE: 'USERS_SCHEDULE_DELIVERY_FAILURE',

    TIME_SLOTS_REQUEST:'TIME_SLOTS_REQUEST',
    TIME_SLOTS_SUCCESS: 'TIME_SLOTS_SUCCESS',
    TIME_SLOTS_FAILURE: 'TIME_SLOTS_FAILURE',

    PAYMENT_MODE_REQUEST:'PAYMENT_MODE_REQUEST',
    PAYMENT_MODE_SUCCESS: 'PAYMENT_MODE_SUCCESS',
    PAYMENT_MODE_FAILURE: 'PAYMENT_MODE_FAILURE',
};