export const orderConstants = {
    ORDER_REQUEST: 'USERS_ORDER_REQUEST',
    ORDER_SUCCESS: 'USERS_ORDER_SUCCESS',
    ORDER_FAILURE: 'USERS_ORDER_FAILURE',

    ADD_ASSET_REQUEST: 'USERS_ADD_ASSET_REQUEST',
    ADD_ASSET_SUCCESS: 'USERS_ADD_ASSET_SUCCESS',
    ADD_ASSET_FAILURE: 'USERS_ADD_ASSET_FAILURE',
};