export const userConstants = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  OTP_REQUEST: 'USERS_OTP_REQUEST',
  OTP_SUCCESS: 'USERS_OTP_SUCCESS',
  OTP_FAILURE: 'USERS_OTP_FAILURE',

  VERIFY_OTP_REQUEST: 'USERS_VERIFY_OTP_REQUEST',
  VERIFY_OTP_SUCCESS: 'USERS_VERIFY_OTP_SUCCESS',
  VERIFY_OTP_FAILURE: 'USERS_VERIFY_OTP_FAILURE',

  SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',

  FORGET_PASSWORD_REQUEST: 'USERS_FORGET_PASSWORD_REQUEST',
  FORGET_PASSWORD_SUCCESS: 'USERS_FORGET_PASSWORD_SUCCESS',
  FORGET_PASSWORD_FAILURE: 'USERS_FORGET_PASSWORD_FAILURE',

  RESET_PASSWORD_REQUEST: 'USERS_RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'USERS_RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'USERS_RESET_PASSWORD_FAILURE',

  LOGOUT: 'USERS_LOGOUT',
};
